# Generated by Django 6.0.6 on 2026-08-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0003_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='carryover_profit',
            field=models.FloatField(default=0, verbose_name='第7節までの持ち越し収支'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
