# Generated by Django 6.0.6 on 2026-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0004_player_carryover_profit_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='carryover_first_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第7節までの1着回数'),
        ),
        migrations.AddField(
            model_name='player',
            name='carryover_fourth_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第7節までの4着回数'),
        ),
        migrations.AddField(
            model_name='player',
            name='carryover_game_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第7節までの対局数'),
        ),
        migrations.AddField(
            model_name='player',
            name='carryover_second_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第7節までの2着回数'),
        ),
        migrations.AddField(
            model_name='player',
            name='carryover_third_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第7節までの3着回数'),
        ),
    ]
